import type { FbotArticle } from '@/lib/fbot/types'
import { FBOT_GREETING as GREETING } from '@/lib/fbot/voice'
import { parseAdminPath } from '@/lib/fbot/context'

export const FBOT_GREETING = GREETING

export const FBOT_ARTICLES: FbotArticle[] = [
  {
    id: 'fbot',
    title: 'FBot (Forgedbot)',
    routes: ['/admin'],
    keywords: ['fbot', 'forgedbot', 'helper', 'assistant', 'chat', 'bot'],
    aliases: ['who are you', 'what is fbot', 'forgedbot', 'help me'],
    body: [
      'I am FBot, the admin helper for this site — catalog and live records only, no AI.',
      'Click the F badge to open this window. Drag the badge or the window.',
      'X or Escape closes the chat. Hide FBot tucks me to an edge tab.',
      'Ask how-tos (“How do I record a track?”) or live facts (“What is the next blog?”).',
    ].join('\n'),
    links: [{ label: 'Dashboard', href: '/admin' }],
  },
  {
    id: 'here',
    title: 'Where you are in the admin',
    routes: ['/admin'],
    keywords: ['here', 'this', 'page', 'where', 'dashboard', 'home'],
    aliases: ['what is this page', 'where am i', 'dashboard'],
    page: true,
    body: [
      'This is the dashboard — home of the admin.',
      'Cards: blog counts, drafts, subscribers, live campaigns, gifts to confirm.',
      'Attention Inbox lists what needs a human next.',
      'Use the left nav to open each desk.',
    ].join('\n'),
    links: [{ label: 'Dashboard', href: '/admin' }],
  },
  {
    id: 'next-blog',
    title: 'What to publish next',
    routes: ['/admin/studio', '/admin/blog'],
    keywords: ['next', 'blog', 'post', 'upcoming', 'topic', 'schedule', 'write', 'publish'],
    aliases: ['whats the next blog', "what's the next blog", 'next blog about', 'upcoming post', 'what should i write', 'what is the next topic'],
    body: [
      'The next piece of work lives in Studio, not only in Blog.',
      'Open Studio for planned topics (title, talking points, scheduled date).',
      'Open Blog for drafts and scheduled posts.',
      'I attach the live next topic and next draft when you ask.',
    ].join('\n'),
    links: [
      { label: 'Studio topics', href: '/admin/studio' },
      { label: 'Blog', href: '/admin/blog' },
    ],
  },
  {
    id: 'write-blog',
    title: 'How to write and publish a blog post',
    routes: ['/admin/blog', '/admin/studio'],
    keywords: ['write', 'blog', 'post', 'draft', 'publish', 'editor', 'new'],
    aliases: ['how do i write a blog', 'publish a post', 'new blog post', 'how do i publish a post'],
    body: [
      'Open Blog → New, or pull a Studio topic into a post.',
      'Write in the block editor. Add excerpt, cover, SEO title and description.',
      'Mark survivor consent if the post uses lived experience.',
      'Set status: draft → scheduled (pick a date) or published.',
      'Turn on notify subscribers only if this post should email the list.',
      'Link the Studio topic so the calendar stays honest.',
    ].join('\n'),
    links: [
      { label: 'New post', href: '/admin/blog/new' },
      { label: 'All posts', href: '/admin/blog' },
    ],
  },
  {
    id: 'studio',
    title: 'Studio — one calendar for blog, social, and podcast',
    routes: ['/admin/studio'],
    keywords: ['studio', 'topic', 'talking', 'points', 'calendar', 'clips', 'planned'],
    aliases: ['studio topics', 'content calendar', 'talking points'],
    body: [
      'Studio is the planning desk.',
      'Create a topic. Add talking points. Set scheduled_on.',
      'Status: idea → planned → in production → published.',
      'Open a topic to attach a blog post, social clips, and a podcast episode.',
      'Production room can pull a planned topic straight into a recording.',
    ].join('\n'),
    links: [{ label: 'Studio', href: '/admin/studio' }],
  },
  {
    id: 'record-track',
    title: 'How to record a track',
    routes: ['/admin/podcast'],
    tabs: ['studio'],
    keywords: ['record', 'recording', 'mic', 'track', 'take', 'punch', 'studio', 'production', 'microphone', 'arm'],
    aliases: ['how do i record', 'how do i record a track', 'start recording', 'record podcast', 'new take', 'open production room'],
    body: [
      'Open Podcast → Production room. Open or create the episode.',
      'Put on headphones. Cue mix is on so other lanes play in your ears, not into the mic.',
      'Add a Person if needed. Arm that person (R).',
      'Set punch: After the mix (guest after host), After my last take (pickup), At playhead, or From start.',
      'Press Record new take (or R). Preroll plays, then you are live. Stop when done.',
      'A new take lands on its own lane. Leave Replace armed clip off unless you mean to overwrite.',
    ].join('\n'),
    links: [
      { label: 'Production room', href: '/admin/podcast?tab=studio' },
      { label: 'Podcast desk', href: '/admin/podcast' },
    ],
  },
  {
    id: 'dual-mics',
    title: 'Record Host and Guest on two mics',
    routes: ['/admin/podcast'],
    tabs: ['studio'],
    keywords: ['host', 'guest', 'two', 'mics', 'microphones', 'both', 'dual', 'lanes'],
    aliases: ['host and guest', 'two mics', 'record host and guest', 'dual record'],
    body: [
      'Add Host and Guest as two people. Assign a different microphone to each.',
      'Arm both people.',
      'Punch After the mix if Guest should start when Host’s mix ends. Punch At playhead to overlap.',
      'Record once — both lanes capture together.',
      'If Chrome reuses one mic, the desk will stop you until each person has a distinct device.',
    ].join('\n'),
    links: [{ label: 'Production room', href: '/admin/podcast?tab=studio' }],
  },
  {
    id: 'remote-guest',
    title: 'Invite a remote guest',
    routes: ['/admin/podcast'],
    tabs: ['studio'],
    keywords: ['invite', 'remote', 'guest', 'link', 'booth', 'webrtc', 'portal'],
    aliases: ['invite guest', 'send guest link', 'remote guest', 'guest portal'],
    body: [
      'In the Production room, Remote guest → Create invite. Copy the link. It expires; Revoke kills it.',
      'Guest opens the link (no admin login). They enter a name, pick a mic, confirm headphones, Join booth.',
      'You keep Record, punch, FX, mix, and export. Guest gets camera on/off, mute, self-view, and a local camera backup.',
      'Arm Host so they hear you. Guest audio lands on the Guest lane at the shared punch. Their camera lands on the Guest camera lane if they turn it on.',
      'If the live link is thin, Lay uploaded guest take / Lay uploaded guest camera drops their local backup on the Guest lanes.',
    ].join('\n'),
    links: [{ label: 'Production room', href: '/admin/podcast?tab=studio' }],
  },
  {
    id: 'edit-track',
    title: 'How to edit a recorded track',
    routes: ['/admin/podcast'],
    tabs: ['studio'],
    keywords: ['edit', 'trim', 'split', 'offset', 'fade', 'effect', 'mute', 'solo', 'pan', 'volume', 'waveform'],
    aliases: ['how do i edit a recorded track', 'edit take', 'trim audio', 'move a take'],
    body: [
      'Select the take. The waveform is that clip. Start / clock is where it sits on the session.',
      'Volume, pan, fade in/out are per take. M mute, S solo, R arm.',
      'Split at playhead cuts one take into two. Bounce track copies a processed stem.',
      'Effects rack rewrites the selected clip (gate, room, hall, compress, and so on). Undo is in the transport.',
      'Drop SFX at the playhead. Save mix MP3 when the master region is right — RSS uses that file, not the lanes.',
    ].join('\n'),
    links: [{ label: 'Production room', href: '/admin/podcast?tab=studio' }],
  },
  {
    id: 'punch-in',
    title: 'Punch-in and coming in after another voice',
    routes: ['/admin/podcast'],
    tabs: ['studio'],
    keywords: ['punch', 'overdub', 'preroll', 'after', 'mix', 'playhead', 'cue', 'headphones'],
    aliases: ['punch in', 'after last take', 'after the mix', 'come in after', 'second track'],
    body: [
      'Cue mix plays other lanes in headphones while you record.',
      'After the mix: new take starts when the current mix ends — use this when Guest follows Host.',
      'After my last take: pickup on that person’s previous audio (falls back to mix end if they have none).',
      'At playhead: punch at the mix cursor.',
      'From start: hear the whole mix from 0:00 and wait; silence at the front of the take is the wait.',
      'Leave Replace armed clip off to keep every take.',
    ].join('\n'),
    links: [{ label: 'Production room', href: '/admin/podcast?tab=studio' }],
  },
  {
    id: 'session-save',
    title: 'Save and recover a recording session',
    routes: ['/admin/podcast'],
    tabs: ['studio'],
    keywords: ['session', 'save', 'recover', 'indexeddb', 'reload', 'lanes'],
    aliases: ['save session', 'recover session', 'lost takes'],
    body: [
      'Takes live in this browser until you save a mix or restore a session.',
      'If the desk offers Recover session after a reload, restore it before recording over it.',
      'Save mix MP3 (hosted) is what the public episode uses.',
      'Download stems zip if you need wavs of each lane.',
    ].join('\n'),
    links: [{ label: 'Production room', href: '/admin/podcast?tab=studio' }],
  },
  {
    id: 'save-publish-podcast',
    title: 'Save a mix and publish an episode',
    routes: ['/admin/podcast'],
    tabs: ['studio'],
    keywords: ['save', 'mix', 'mp3', 'wav', 'publish', 'rss', 'apple', 'spotify', 'export'],
    aliases: ['save mix', 'publish episode', 'rss feed', 'save mix and publish'],
    body: [
      'Set the master In/Out region in the production room.',
      'Save mix MP3 (hosted). That writes audio_url, file size, and duration on the episode.',
      'Add square cover art, episode number, summary, show notes.',
      'Publish now, or schedule a time.',
      'Public feed is /podcast/rss.xml — submit that once to Apple, Spotify, and Amazon.',
    ].join('\n'),
    links: [
      { label: 'Production room', href: '/admin/podcast?tab=studio' },
      { label: 'RSS', href: '/podcast/rss.xml' },
    ],
  },
  {
    id: 'podcast-desk',
    title: 'Podcast desk — show, distribution, analytics',
    routes: ['/admin/podcast'],
    keywords: ['podcast', 'show', 'distribution', 'apple', 'spotify', 'private', 'embed', 'chapters'],
    aliases: ['submit to apple', 'podcast settings'],
    body: [
      'Tabs: Production room, Episodes, Show, Distribution, Analytics, Private feed, Embeds + RSS.',
      'Show holds title, author, categories, cover.',
      'Distribution tracks each directory.',
      'Analytics is first-party plays from our beacons, not Apple’s dashboard.',
      'Private feed is a token RSS for reviewers.',
    ].join('\n'),
    links: [{ label: 'Podcast', href: '/admin/podcast' }],
  },
  {
    id: 'visits',
    title: 'Visits and traffic',
    routes: ['/admin/analytics'],
    keywords: ['visit', 'visits', 'traffic', 'pageview', 'pageviews', 'ga4', 'analytics', 'today', 'sessions', 'users'],
    aliases: ['how many visits today', 'visits today', 'site traffic', 'page views'],
    body: [
      'I cannot give a live “visits today” count from GA4 — that Data API is not wired here yet.',
      'Open Analytics for subscriber and post counts.',
      'Podcast plays today come from our own beacons when I can read them.',
      'Set the public Measurement ID in Settings for consented tracking.',
    ].join('\n'),
    links: [
      { label: 'Analytics', href: '/admin/analytics' },
      { label: 'Podcast analytics', href: '/admin/podcast?tab=analytics' },
      { label: 'Settings', href: '/admin/settings' },
    ],
  },
  {
    id: 'campaigns',
    title: 'Fundraising campaigns',
    routes: ['/admin/campaigns'],
    keywords: ['campaign', 'fundrais', 'donate', 'gift', 'zeffy', 'thermometer', 'goal', 'live'],
    aliases: ['how do i go live', 'start a campaign'],
    body: [
      'Campaigns → New. Pick a template. Fill story, goal, Zeffy URL.',
      'Safety tab must pass before Go live — the status dropdown cannot skip that.',
      'Public page is /campaigns/[slug].',
      'Gifts are self-reported after Zeffy. Confirm or void them on the desk.',
      'Advocates get a personal /f/[slug] link.',
      'Attach an ads campaign to copy a UTM landing URL.',
    ].join('\n'),
    links: [
      { label: 'Campaigns', href: '/admin/campaigns' },
      { label: 'New campaign', href: '/admin/campaigns/new' },
      { label: 'Public campaigns', href: '/campaigns' },
    ],
  },
  {
    id: 'ads',
    title: 'Ad analytics and UTMs',
    routes: ['/admin/ads'],
    keywords: ['ads', 'ad', 'spend', 'roas', 'utm', 'meta', 'google', 'return'],
    aliases: ['ad analytics', 'how is the ad doing', 'utm link', 'how do utms work', 'where is ad spend'],
    body: [
      'Open Ad analytics.',
      'Log spend and returns on the campaign.',
      'Optionally attach a fundraising campaign.',
      'Copy the UTM landing URL for ads.',
      'Dignity checkboxes stay off until you mark them.',
      'Research-report preview is admin-only.',
    ].join('\n'),
    links: [{ label: 'Ad analytics', href: '/admin/ads' }],
  },
  {
    id: 'subscribers',
    title: 'Subscribers and newsletters',
    routes: ['/admin/subscribers', '/admin/newsletters'],
    keywords: ['subscriber', 'newsletter', 'email', 'list', 'notify', 'send'],
    aliases: ['send newsletter'],
    body: [
      'Subscribers is the list (active / unsubscribed).',
      'Newsletters → New to compose, then Send.',
      'Blog publish can notify the list if send-notification is on for that post.',
      'Counts I quote are from newsletter_subscribers.',
    ].join('\n'),
    links: [
      { label: 'Subscribers', href: '/admin/subscribers' },
      { label: 'Newsletters', href: '/admin/newsletters' },
    ],
  },
  {
    id: 'seo',
    title: 'SEO Center',
    routes: ['/admin/seo'],
    keywords: ['seo', 'crawl', 'meta', 'sitemap', 'red', 'audit'],
    aliases: ['seo health', 'run crawl'],
    body: [
      'Open SEO Center for the last crawl report.',
      'Green / yellow / red are from `npm run seo:crawl`.',
      'Fix titles and meta on each content item, then recrawl.',
      'Sitemap includes public campaigns.',
    ].join('\n'),
    links: [{ label: 'SEO Center', href: '/admin/seo' }],
  },
  {
    id: 'content-pages',
    title: 'Site pages (Content)',
    routes: ['/admin/content'],
    keywords: ['content', 'page', 'about', 'services', 'duplicate'],
    aliases: ['edit a page', 'site pages', 'how do i edit a page'],
    body: [
      'Content is site pages, separate from Blog.',
      'Open an item to edit blocks, SEO, and publish state.',
      'Duplicate exists on the item.',
      'Careers has its own desk.',
    ].join('\n'),
    links: [{ label: 'Content', href: '/admin/content' }],
  },
  {
    id: 'social',
    title: 'Social desk',
    routes: ['/admin/social'],
    keywords: ['social', 'instagram', 'facebook', 'clip', 'caption'],
    aliases: ['post to instagram', 'social clips', 'how do social clips work'],
    body: [
      'Social holds connected accounts and campaigns.',
      'Open a Studio topic to spawn short clips (9:16 and so on) with captions.',
      'This desk keeps copy and status with the topic — it does not replace Meta’s scheduler.',
    ].join('\n'),
    links: [{ label: 'Social', href: '/admin/social' }],
  },
  {
    id: 'careers',
    title: 'Careers listings',
    routes: ['/admin/careers'],
    keywords: ['career', 'job', 'listing', 'hiring'],
    aliases: ['post a job'],
    body: [
      'Open Careers.',
      'Inactive listings also show on the dashboard Attention Inbox.',
      'Toggle active when a role should appear on the public site.',
    ].join('\n'),
    links: [{ label: 'Careers', href: '/admin/careers' }],
  },
  {
    id: 'users-settings',
    title: 'Users, login, and settings',
    routes: ['/admin/users', '/admin/settings', '/login'],
    keywords: ['user', 'admin', 'login', 'password', 'settings', 'ga4', 'measurement'],
    aliases: ['change settings', 'who can log in', 'open settings'],
    body: [
      'Only emails in admin_users with role admin or owner get this portal.',
      'Open Users to add or remove that list.',
      'Open Settings for site-level values, including the public GA4 measurement ID.',
      'Login honors ?redirect= so you return to the page you asked for.',
    ].join('\n'),
    links: [
      { label: 'Users', href: '/admin/users' },
      { label: 'Settings', href: '/admin/settings' },
    ],
  },
  {
    id: 'donate',
    title: 'Donate page and EIN',
    routes: ['/admin', '/admin/campaigns'],
    keywords: ['donate', 'ein', 'zeffy', 'charter', 'irs'],
    aliases: ['ein number', 'donate url'],
    body: [
      'Public donate uses ZEFFY_DONATE_URL.',
      'Org EIN is 39-3438993 (Ohio charter 5445768).',
      'Named campaigns live under /campaigns.',
      'The donate page still works when no campaign is live.',
    ].join('\n'),
    links: [
      { label: 'Donate', href: '/donate' },
      { label: 'Campaigns', href: '/admin/campaigns' },
    ],
  },
  {
    id: 'here-podcast-studio',
    title: 'This screen — Production room',
    page: true,
    routes: ['/admin/podcast?tab=studio'],
    tabs: ['studio'],
    keywords: ['studio', 'production', 'room', 'here', 'screen', 'tab'],
    aliases: ['production room', 'this tab', 'this screen'],
    body: [
      'You are in Podcast → Production room.',
      'Left: episode queue. Center: people, takes, waveform, punch mode, cue mix.',
      'Arm a person, set punch, Record (R). Headphones on so the mix does not leak into the mic.',
      'Save mix MP3 (hosted) is what RSS uses. Recover session if Chrome reloaded on you.',
    ].join('\n'),
    links: [{ label: 'Production room', href: '/admin/podcast?tab=studio' }],
  },
  {
    id: 'here-podcast-episodes',
    title: 'This screen — Episodes pipeline',
    page: true,
    routes: ['/admin/podcast?tab=episodes'],
    tabs: ['episodes'],
    keywords: ['episodes', 'pipeline', 'board', 'here', 'screen'],
    aliases: ['episode board', 'episode pipeline'],
    body: [
      'You are in Podcast → Episodes.',
      'Columns are draft → recording → editing → review → scheduled → published.',
      'Create an episode here, or open one to edit show notes, cover, and schedule.',
      'Open Production room on an episode to record audio.',
    ].join('\n'),
    links: [{ label: 'Episodes', href: '/admin/podcast?tab=episodes' }],
  },
  {
    id: 'here-podcast-show',
    title: 'This screen — Show settings',
    page: true,
    routes: ['/admin/podcast?tab=show'],
    tabs: ['show'],
    keywords: ['show', 'title', 'author', 'category', 'cover', 'explicit'],
    aliases: ['show settings', 'podcast title'],
    body: [
      'You are in Podcast → Show.',
      'This is the RSS <channel>: title, author, summary, categories, cover, explicit flag.',
      'Save here before you submit the feed to Apple or Spotify.',
    ].join('\n'),
    links: [{ label: 'Show', href: '/admin/podcast?tab=show' }],
  },
  {
    id: 'here-studio',
    title: 'This screen — Studio',
    page: true,
    routes: ['/admin/studio'],
    keywords: ['studio', 'here', 'screen', 'topics'],
    aliases: ['this screen', 'this page'],
    body: [
      'You are in Studio — the content calendar.',
      'Each topic can grow a blog post, social clips, and a podcast episode.',
      'Open a topic to edit talking points, then Create episode to jump into Production room.',
    ].join('\n'),
    links: [{ label: 'Studio', href: '/admin/studio' }],
  },
  {
    id: 'here-blog',
    title: 'This screen — Blog board',
    page: true,
    routes: ['/admin/blog'],
    keywords: ['blog', 'here', 'screen', 'posts'],
    aliases: ['this screen', 'blog board'],
    body: [
      'You are on the Blog production board.',
      'Filter by status. New Post opens the editor.',
      'Survivor consent is required for lived-experience posts before publish.',
    ].join('\n'),
    links: [{ label: 'Blog', href: '/admin/blog' }],
  },
  {
    id: 'here-campaigns',
    title: 'This screen — Campaigns',
    page: true,
    routes: ['/admin/campaigns'],
    keywords: ['campaigns', 'here', 'screen', 'hub'],
    aliases: ['campaign hub'],
    body: [
      'You are on the Campaigns hub.',
      'New campaign starts from a template. Open a row for Story / Give / Safety / Gifts / Advocates.',
      'Safety must pass before Go live.',
    ].join('\n'),
    links: [{ label: 'Campaigns', href: '/admin/campaigns' }],
  },
  {
    id: 'here-campaign-desk',
    title: 'This screen — Campaign desk',
    page: true,
    routes: ['/admin/campaigns'],
    keywords: ['story', 'give', 'safety', 'share', 'gifts', 'advocates', 'desk'],
    aliases: ['campaign desk', 'safety tab'],
    body: [
      'This desk has tabs: Story, Give, Safety, Share, Gifts, Advocates.',
      'Safety: dignity / consent checkboxes — required before Go live.',
      'Gifts: confirm or void self-reported Zeffy gifts.',
      'Advocates: personal /f/[slug] pages that roll up to this campaign.',
    ].join('\n'),
    links: [{ label: 'Campaigns', href: '/admin/campaigns' }],
  },
  {
    id: 'here-campaign-safety',
    title: 'This screen — Safety',
    page: true,
    routes: ['/admin/campaigns'],
    tabs: ['safety'],
    keywords: ['safety', 'here', 'screen', 'dignity'],
    aliases: ['this tab', 'safety screen'],
    body: [
      'You are on this campaign’s Safety tab.',
      'Checkboxes: dignity / consent, no identifying details without permission, graphic-detail review.',
      'Zeffy URL and story must be filled. Go live stays locked until this list is empty.',
    ].join('\n'),
    links: [{ label: 'Campaigns', href: '/admin/campaigns' }],
  },
  {
    id: 'here-campaign-gifts',
    title: 'This screen — Gifts',
    page: true,
    routes: ['/admin/campaigns'],
    tabs: ['gifts'],
    keywords: ['gifts', 'here', 'screen', 'pending'],
    aliases: ['gifts tab', 'this tab'],
    body: [
      'You are on this campaign’s Gifts tab.',
      'Pending rows need Confirm (receipt matches) or Void (test / duplicate).',
      'You can also log a gift here if someone gave off-page.',
    ].join('\n'),
    links: [{ label: 'Campaigns', href: '/admin/campaigns' }],
  },
  {
    id: 'here-campaign-advocates',
    title: 'This screen — Advocates',
    page: true,
    routes: ['/admin/campaigns'],
    tabs: ['advocates'],
    keywords: ['advocates', 'here', 'screen'],
    aliases: ['advocates tab', 'this tab'],
    body: [
      'You are on this campaign’s Advocates tab.',
      'Add a name and optional goal. They get /campaigns/[slug]/f/[fundraiserSlug].',
      'Share that URL. Gifts tagged to them still count on the main thermometer.',
    ].join('\n'),
    links: [{ label: 'Campaigns', href: '/admin/campaigns' }],
  },
  {
    id: 'here-episode-editor',
    title: 'This screen — Episode editor',
    page: true,
    routes: ['/admin/podcast'],
    keywords: ['episode', 'editor', 'show notes', 'chapters', 'cover', 'here'],
    aliases: ['episode editor', 'this episode'],
    body: [
      'This is one episode’s metadata — not the Production room.',
      'Edit title, number, summary, show notes, guest, cover, chapters, and schedule.',
      'Open Production room from Podcast → Production room with this episode selected to record.',
      'Publish or schedule only after a hosted mix MP3 is on the episode.',
    ].join('\n'),
    links: [{ label: 'Production room', href: '/admin/podcast?tab=studio' }],
  },
  {
    id: 'here-topic',
    title: 'This screen — Topic workspace',
    page: true,
    routes: ['/admin/studio'],
    keywords: ['topic', 'workspace', 'talking', 'clips', 'here'],
    aliases: ['this topic', 'topic workspace'],
    body: [
      'This is one Studio topic.',
      'Talking points are one per line. Status and scheduled_on drive the calendar.',
      'Spawn a blog post, 9:16 clips, or Create episode into Production room.',
    ].join('\n'),
    links: [{ label: 'Studio', href: '/admin/studio' }],
  },
  {
    id: 'here-blog-post',
    title: 'This screen — Blog editor',
    page: true,
    routes: ['/admin/blog'],
    keywords: ['editor', 'blocks', 'seo', 'preview', 'here', 'post'],
    aliases: ['this post', 'blog editor'],
    body: [
      'This is one blog post. Tabs: Content, SEO, Preview.',
      'Autosave runs while you type. Publish uses the checklist on the right.',
      'Survivor consent is required for lived-experience / impact stories.',
      'Notify subscribers only if this post should email the list.',
    ].join('\n'),
    links: [{ label: 'Blog', href: '/admin/blog' }],
  },
  {
    id: 'here-ads',
    title: 'This screen — Ad analytics',
    page: true,
    routes: ['/admin/ads'],
    keywords: ['ads', 'here', 'screen', 'spend', 'roas'],
    aliases: ['ad desk', 'this screen'],
    body: [
      'You are on Ad analytics.',
      'Create a campaign, log spend and returns, copy a UTM landing URL.',
      'Dignity checkboxes stay off until a human marks them.',
      'Peer research is on this desk too — it is not live Meta spend.',
    ].join('\n'),
    links: [{ label: 'Ad analytics', href: '/admin/ads' }],
  },
  {
    id: 'here-analytics',
    title: 'This screen — Analytics',
    page: true,
    routes: ['/admin/analytics'],
    keywords: ['analytics', 'here', 'screen', 'ga4'],
    aliases: ['analytics desk', 'this screen'],
    body: [
      'You are on Analytics.',
      'Cards here: subscribers, new in 7 days, published posts.',
      'GA4 sessions are only shown if the Data API is connected — today it is not, so I will not invent visits.',
      'Podcast plays live under Podcast → Analytics.',
    ].join('\n'),
    links: [
      { label: 'Analytics', href: '/admin/analytics' },
      { label: 'Podcast analytics', href: '/admin/podcast?tab=analytics' },
    ],
  },
  {
    id: 'here-subscribers',
    title: 'This screen — Subscribers',
    page: true,
    routes: ['/admin/subscribers'],
    keywords: ['subscribers', 'here', 'list'],
    aliases: ['subscriber list', 'this screen'],
    body: [
      'This is the email list: active and unsubscribed.',
      'Compose and send from Newsletters, not from this table.',
    ].join('\n'),
    links: [
      { label: 'Subscribers', href: '/admin/subscribers' },
      { label: 'Newsletters', href: '/admin/newsletters' },
    ],
  },
  {
    id: 'here-newsletters',
    title: 'This screen — Newsletters',
    page: true,
    routes: ['/admin/newsletters'],
    keywords: ['newsletters', 'here', 'compose'],
    aliases: ['newsletter desk', 'this screen'],
    body: [
      'Monthly newsletter issues live here: draft, scheduled, sent.',
      'New → title, month, year → write → Send emails active subscribers.',
    ].join('\n'),
    links: [{ label: 'New newsletter', href: '/admin/newsletters/new' }],
  },
  {
    id: 'here-seo',
    title: 'This screen — SEO Center',
    page: true,
    routes: ['/admin/seo'],
    keywords: ['seo', 'here', 'crawl'],
    aliases: ['seo desk', 'this screen'],
    body: [
      'Last crawl report: green / yellow / red.',
      'Fix titles and meta on the content item, then recrawl (`npm run seo:crawl`).',
    ].join('\n'),
    links: [{ label: 'SEO Center', href: '/admin/seo' }],
  },
  {
    id: 'here-social',
    title: 'This screen — Social',
    page: true,
    routes: ['/admin/social'],
    keywords: ['social', 'here', 'accounts'],
    aliases: ['social desk', 'this screen'],
    body: [
      'Accounts and social campaigns live here.',
      '9:16 clip canvases still live on the Studio topic.',
      'This desk does not post to Meta for you.',
    ].join('\n'),
    links: [{ label: 'Social', href: '/admin/social' }],
  },
  {
    id: 'here-careers',
    title: 'This screen — Careers',
    page: true,
    routes: ['/admin/careers'],
    keywords: ['careers', 'jobs', 'here'],
    aliases: ['jobs desk', 'this screen'],
    body: [
      'Job listings. Toggle active for the public careers page.',
      'Inactive roles also show on the dashboard Attention Inbox.',
    ].join('\n'),
    links: [{ label: 'Careers', href: '/admin/careers' }],
  },
  {
    id: 'here-content',
    title: 'This screen — Site pages',
    page: true,
    routes: ['/admin/content'],
    keywords: ['content', 'pages', 'here'],
    aliases: ['site pages', 'this screen'],
    body: [
      'These are site pages (About, Services), not blog posts.',
      'Open an item for blocks, SEO, and publish. Duplicate is on the item.',
    ].join('\n'),
    links: [{ label: 'Content', href: '/admin/content' }],
  },
  {
    id: 'here-users',
    title: 'This screen — Users',
    page: true,
    routes: ['/admin/users'],
    keywords: ['users', 'admins', 'here'],
    aliases: ['users desk', 'this screen'],
    body: [
      'Emails in this list with role admin or owner can open /admin.',
      'Add the email exactly as they will sign in. They use /login.',
    ].join('\n'),
    links: [{ label: 'Users', href: '/admin/users' }],
  },
  {
    id: 'here-settings',
    title: 'This screen — Settings',
    page: true,
    routes: ['/admin/settings'],
    keywords: ['settings', 'here', 'measurement'],
    aliases: ['settings desk', 'this screen'],
    body: [
      'Organization, contact, public GA4 Measurement ID, and social URLs.',
      'This is not the GA4 Data API — visits today still cannot be quoted from here.',
    ].join('\n'),
    links: [{ label: 'Settings', href: '/admin/settings' }],
  },
  {
    id: 'here-podcast-distribution',
    title: 'This screen — Distribution',
    page: true,
    routes: ['/admin/podcast?tab=distribution'],
    tabs: ['distribution'],
    keywords: ['distribution', 'here', 'directories'],
    aliases: ['distribution tab', 'this tab'],
    body: [
      'Track each directory: not started → submitted → in review → live.',
      'Need a saved Show record, at least one published episode with hosted MP3, and /podcast/rss.xml.',
    ].join('\n'),
    links: [{ label: 'Distribution', href: '/admin/podcast?tab=distribution' }],
  },
  {
    id: 'here-podcast-analytics',
    title: 'This screen — Podcast analytics',
    page: true,
    routes: ['/admin/podcast?tab=analytics'],
    tabs: ['analytics'],
    keywords: ['plays', 'downloads', 'here', 'beacons'],
    aliases: ['podcast analytics tab', 'this tab'],
    body: [
      'First-party plays from our beacons — not Apple’s dashboard.',
      'Ask me “podcast plays today” for the live count when the table is readable.',
    ].join('\n'),
    links: [{ label: 'Podcast analytics', href: '/admin/podcast?tab=analytics' }],
  },
  {
    id: 'here-podcast-private',
    title: 'This screen — Private feed',
    page: true,
    routes: ['/admin/podcast?tab=private'],
    tabs: ['private'],
    keywords: ['private', 'token', 'here'],
    aliases: ['private tab', 'this tab'],
    body: [
      'Token RSS for reviewers. Not the public /podcast/rss.xml.',
      'Share only with people who should hear unpublished audio.',
    ].join('\n'),
    links: [{ label: 'Private feed', href: '/admin/podcast?tab=private' }],
  },
  {
    id: 'episode-metadata',
    title: 'Edit episode show notes, chapters, and schedule',
    routes: ['/admin/podcast'],
    keywords: ['chapters', 'show notes', 'guest', 'cover', 'schedule', 'episode number', 'metadata'],
    aliases: ['add chapters', 'show notes', 'schedule episode', 'episode cover'],
    body: [
      'Open the episode from Podcast → Episodes (not Production room).',
      'Fill episode number, summary, show notes, guest, square cover.',
      'Chapters: title + start time. They go into RSS.',
      'Schedule a time or publish now — only after Save mix MP3 (hosted) wrote audio_url.',
    ].join('\n'),
    links: [{ label: 'Episodes', href: '/admin/podcast?tab=episodes' }],
  },
  {
    id: 'shortcuts',
    title: 'Production room keyboard shortcuts',
    routes: ['/admin/podcast'],
    tabs: ['studio'],
    keywords: ['shortcut', 'keyboard', 'keys', 'space', 'hotkey'],
    aliases: ['keyboard shortcuts', 'what keys', 'hotkeys'],
    body: [
      'Space plays or pauses the mix.',
      'R starts or stops record on the armed person.',
      'S splits the selected take at the playhead.',
      'Delete cuts a hole in the selected range.',
      '1–0 drops SFX at the playhead (1 ding … 0 room air).',
      'C marks a chapter at the playhead.',
    ].join('\n'),
    links: [{ label: 'Production room', href: '/admin/podcast?tab=studio' }],
  },
  {
    id: 'effects',
    title: 'Effects rack',
    routes: ['/admin/podcast'],
    tabs: ['studio'],
    keywords: ['effect', 'effects', 'reverb', 'gate', 'compress', 'deess', 'hall', 'room', 'normalize'],
    aliases: ['effects rack', 'add reverb', 'noise gate', 'de-ess'],
    body: [
      'Select a take, then use the effects rack. Each effect bakes into that clip. Undo is in the transport.',
      'Cleanup: Normalize, Noise gate, Rumble cut, Presence, De-ess, Compress, Limiter.',
      'Space: Room, Hall, Echo, Chorus, Telephone, Tape warmth.',
      'Edit: Strip silence, Reverse.',
      'Bounce track if you want a processed stem without replacing the original take — unless Replace is on.',
    ].join('\n'),
    links: [{ label: 'Production room', href: '/admin/podcast?tab=studio' }],
  },
  {
    id: 'sfx',
    title: 'Sound effects pad',
    routes: ['/admin/podcast'],
    tabs: ['studio'],
    keywords: ['sfx', 'sound', 'ding', 'chime', 'stinger', 'whoosh', 'pad'],
    aliases: ['sound effects', 'sfx pad', 'drop a ding'],
    body: [
      'Open the SFX pad in Production room. Click a pad or press 1–0.',
      'Pads: Ding, Chime, Notify, Click, Whoosh, Sweep, Stinger, Riser, Heartbeat, Room air.',
      'The hit lands at the playhead on an SFX lane — it is not recorded through the mic.',
    ].join('\n'),
    links: [{ label: 'Production room', href: '/admin/podcast?tab=studio' }],
  },
  {
    id: 'lufs-stems',
    title: 'LUFS, mix MP3, WAV, and stems',
    routes: ['/admin/podcast'],
    tabs: ['studio'],
    keywords: ['lufs', 'loudness', 'stems', 'wav', 'mp3', 'normalize', 'master'],
    aliases: ['match lufs', 'download stems', 'save wav', 'how loud'],
    body: [
      'Match −16 LUFS is on by default for podcast masters. Uncheck it only if you already mixed to spec.',
      'Save mix MP3 (hosted) uploads the master and writes audio_url — that is the public file.',
      'Save mix WAV is a local download for archive.',
      'Download stems zip packs each lane as WAV plus the mix MP3.',
    ].join('\n'),
    links: [{ label: 'Production room', href: '/admin/podcast?tab=studio' }],
  },
  {
    id: 'distribution',
    title: 'Submit the show to Apple, Spotify, Amazon',
    routes: ['/admin/podcast'],
    tabs: ['distribution', 'embeds'],
    keywords: ['apple', 'spotify', 'amazon', 'directory', 'submit', 'distribution'],
    aliases: ['submit to apple', 'submit to spotify', 'podcast directories'],
    body: [
      'Open Podcast → Show. Fill title, author, categories, square cover, explicit flag. Save.',
      'Publish at least one episode with hosted MP3 audio.',
      'Copy /podcast/rss.xml from Embeds + RSS.',
      'Open Distribution and mark each directory: not started → submitted → in review → live.',
      'Apple Podcasts Connect, Spotify for Podcasters, and Amazon Music all ingest that RSS.',
    ].join('\n'),
    links: [
      { label: 'Distribution', href: '/admin/podcast?tab=distribution' },
      { label: 'RSS', href: '/podcast/rss.xml' },
    ],
  },
  {
    id: 'private-feed',
    title: 'Private review feed',
    routes: ['/admin/podcast'],
    tabs: ['private'],
    keywords: ['private', 'review', 'token', 'embargo', 'preview'],
    aliases: ['private feed', 'reviewer rss', 'token feed'],
    body: [
      'Open Podcast → Private feed.',
      'This is a token RSS for reviewers — not the public /podcast/rss.xml.',
      'Share the private URL only with people who should hear unpublished audio.',
    ].join('\n'),
    links: [{ label: 'Private feed', href: '/admin/podcast?tab=private' }],
  },
  {
    id: 'campaign-safety',
    title: 'Campaign safety and Go live',
    routes: ['/admin/campaigns'],
    tabs: ['safety'],
    keywords: ['safety', 'consent', 'dignity', 'identifying', 'go', 'live', 'gate'],
    aliases: ['safety tab', 'dignity gate', 'how do i go live'],
    body: [
      'Open the campaign → Safety.',
      'Check: no identifying survivor details without consent; dignity / consent gate; Zeffy URL present; story filled.',
      'Press Go live only after Safety is clean. The status dropdown cannot skip that.',
      'Public URL is /campaigns/[slug].',
    ].join('\n'),
    links: [{ label: 'Campaigns', href: '/admin/campaigns' }],
  },
  {
    id: 'campaign-gifts',
    title: 'Confirm or void a gift',
    routes: ['/admin/campaigns'],
    tabs: ['gifts'],
    keywords: ['gift', 'confirm', 'void', 'zeffy', 'pending', 'donor'],
    aliases: ['confirm gift', 'void gift', 'gifts to confirm'],
    body: [
      'Open the campaign → Gifts.',
      'Donors self-report after Zeffy. Status starts pending.',
      'Confirm when the Zeffy receipt matches. Void duplicates or tests.',
      'Anonymous gifts hide the name on the public donor wall.',
    ].join('\n'),
    links: [{ label: 'Campaigns', href: '/admin/campaigns' }],
  },
  {
    id: 'campaign-advocates',
    title: 'Advocate / personal fundraiser pages',
    routes: ['/admin/campaigns'],
    tabs: ['advocates'],
    keywords: ['advocate', 'fundraiser', 'personal', 'share', 'slug'],
    aliases: ['advocate page', 'personal fundraiser', 'f slug'],
    body: [
      'Open the campaign → Advocates.',
      'Add a name and optional goal. They get /campaigns/[slug]/f/[fundraiserSlug].',
      'Gifts tagged to that advocate roll up to the parent thermometer.',
      'Share tab copies the public URL and UTM landing link.',
    ].join('\n'),
    links: [{ label: 'Campaigns', href: '/admin/campaigns' }],
  },
  {
    id: 'topic-workspace',
    title: 'Work a Studio topic into blog, clips, and episode',
    routes: ['/admin/studio'],
    keywords: ['topic', 'workspace', 'talking', 'clips', 'bundle', 'create episode'],
    aliases: ['open a topic', 'create episode from topic', 'talking points'],
    body: [
      'Open Studio → a topic.',
      'Edit talking points (one per line). Set scheduled_on and status.',
      'Create or link a blog post from the topic.',
      'Clips: 9:16 canvases for Instagram / TikTok with captions.',
      'Create episode jumps to Production room with that episode selected.',
    ].join('\n'),
    links: [{ label: 'Studio', href: '/admin/studio' }],
  },
  {
    id: 'newsletter-send',
    title: 'Compose and send a newsletter',
    routes: ['/admin/newsletters'],
    keywords: ['compose', 'send', 'newsletter', 'month', 'year', 'draft'],
    aliases: ['send a newsletter', 'compose newsletter', 'new newsletter'],
    body: [
      'Open Newsletters → New.',
      'Set title, month, year. Save draft.',
      'Write the issue, then Send. That emails active subscribers.',
      'Blog publish can also notify the list if that post’s notify box is on.',
    ].join('\n'),
    links: [
      { label: 'Newsletters', href: '/admin/newsletters' },
      { label: 'New newsletter', href: '/admin/newsletters/new' },
    ],
  },
  {
    id: 'settings-deep',
    title: 'What Settings actually change',
    routes: ['/admin/settings'],
    keywords: ['organization', 'contact', 'measurement', 'facebook', 'instagram', 'phone', 'email'],
    aliases: ['site settings', 'measurement id', 'contact email', 'open settings'],
    body: [
      'Settings → General: organization name and site description.',
      'Contact: email, phone, address, service area (public footer / contact).',
      'Analytics: public GA4 Measurement ID (G-…). Cookie consent must be on for it to fire.',
      'Social: Facebook, Instagram, Twitter/X URLs.',
      'Save. This is not the GA4 Data API — I still cannot quote visits today from here.',
    ].join('\n'),
    links: [{ label: 'Settings', href: '/admin/settings' }],
  },
  {
    id: 'blog-consent',
    title: 'Survivor consent on a blog post',
    routes: ['/admin/blog'],
    keywords: ['consent', 'survivor', 'lived', 'experience', 'impact', 'story'],
    aliases: ['survivor consent', 'consent box', 'lived experience'],
    body: [
      'Open the post in Blog.',
      'If the piece uses lived experience, confirm survivor consent before publish.',
      'Impact-story templates expect that checkbox.',
      'Do not publish identifying details without it — same rule as campaign Safety.',
    ].join('\n'),
    links: [{ label: 'Blog', href: '/admin/blog' }],
  },
  {
    id: 'social-accounts',
    title: 'Social accounts and campaigns',
    routes: ['/admin/social'],
    keywords: ['account', 'connect', 'instagram', 'facebook', 'tiktok', 'caption'],
    aliases: ['social accounts', 'connect instagram'],
    body: [
      'Social → Accounts holds connected profiles.',
      'Social → Campaigns groups posts. Studio clips keep 9:16 copy with the topic.',
      'This desk does not publish to Meta for you — it keeps status and captions in one place.',
    ].join('\n'),
    links: [
      { label: 'Social', href: '/admin/social' },
      { label: 'Accounts', href: '/admin/social/accounts' },
    ],
  },
  {
    id: 'users-add',
    title: 'Add an admin user',
    routes: ['/admin/users'],
    keywords: ['add', 'invite', 'owner', 'role', 'email'],
    aliases: ['add an admin', 'invite admin', 'who can log in'],
    body: [
      'Open Users.',
      'Add the email exactly as they will sign in (lowercased).',
      'Role admin or owner. Only those rows pass middleware into /admin.',
      'They log in at /login. Password reset is on that screen.',
    ].join('\n'),
    links: [{ label: 'Users', href: '/admin/users' }],
  },
]

export const PATH_CHIPS: { prefix: string; chips: string[] }[] = [
  { prefix: '/admin/podcast?tab=studio', chips: ['How do I record a track?', 'Keyboard shortcuts', 'Effects rack', 'Record Host and Guest'] },
  { prefix: '/admin/podcast?tab=episodes', chips: ['Episodes needing audio', 'How do I record a track?', 'Save mix and publish'] },
  { prefix: '/admin/podcast?tab=distribution', chips: ['Submit to Apple', 'Where is the RSS?'] },
  { prefix: '/admin/podcast?tab=private', chips: ['Private review feed', 'Episodes needing audio'] },
  { prefix: '/admin/podcast?tab=show', chips: ['Show settings', 'Submit to Apple'] },
  { prefix: '/admin/podcast?tab=embeds', chips: ['Where is the RSS?', 'Submit to Apple'] },
  { prefix: '/admin/podcast?tab=analytics', chips: ['Podcast plays today', 'How many visits today?'] },
  { prefix: '/admin/podcast', chips: ['How do I record a track?', 'How do I edit a recorded track?', 'Record Host and Guest', 'Save mix and publish'] },
  { prefix: '/admin/studio', chips: ['What is the next topic?', 'Create episode from topic', 'How do I write a blog?'] },
  { prefix: '/admin/blog', chips: ['What is the next blog?', 'How do I publish a post?', 'Survivor consent'] },
  { prefix: '/admin/campaigns?tab=safety', chips: ['How do I go live?', 'Confirm a gift', 'Safety tab'] },
  { prefix: '/admin/campaigns?tab=gifts', chips: ['Confirm a gift', 'How do I go live?', 'Gifts to confirm'] },
  { prefix: '/admin/campaigns?tab=advocates', chips: ['Advocate pages', 'How do I go live?', 'Confirm a gift'] },
  { prefix: '/admin/campaigns?tab=share', chips: ['Advocate pages', 'How do I go live?'] },
  { prefix: '/admin/campaigns?tab=give', chips: ['How do I go live?', 'Confirm a gift'] },
  { prefix: '/admin/campaigns?tab=story', chips: ['How do I go live?', 'Confirm a gift', 'Advocate pages'] },
  { prefix: '/admin/campaigns', chips: ['How do I go live?', 'Confirm a gift', 'Advocate pages'] },
  { prefix: '/admin/ads', chips: ['How do UTMs work?', 'Where is ad spend?'] },
  { prefix: '/admin/analytics', chips: ['How many visits today?', 'Subscribers this week'] },
  { prefix: '/admin/subscribers', chips: ['How many subscribers?', 'Send a newsletter'] },
  { prefix: '/admin/seo', chips: ['SEO health', 'Sitemap'] },
  { prefix: '/admin/social', chips: ['How do social clips work?', 'Social accounts'] },
  { prefix: '/admin/content', chips: ['How do I edit a page?', 'What is the next blog?'] },
  { prefix: '/admin/newsletters', chips: ['Send a newsletter', 'How many subscribers?'] },
  { prefix: '/admin/users', chips: ['Add an admin', 'Who can log in?'] },
  { prefix: '/admin/settings', chips: ['Measurement ID', 'Contact email'] },
  { prefix: '/admin', chips: ['What needs attention?', 'What is the next blog?', 'How do I record a track?'] },
]

export function chipsForPath(path: string) {
  const ctx = parseAdminPath(path)
  if (ctx.desk === 'podcast' && ctx.tab) {
    const keyed = PATH_CHIPS.find((row) => row.prefix === `/admin/podcast?tab=${ctx.tab}`)
    if (keyed) return keyed.chips
  }
  if (ctx.desk === 'campaigns' && ctx.tab && /^\/admin\/campaigns\/[^/]+/.test(ctx.pathname)) {
    const keyed = PATH_CHIPS.find((row) => row.prefix === `/admin/campaigns?tab=${ctx.tab}`)
    if (keyed) return keyed.chips
  }
  if (ctx.desk === 'episode') {
    return ['Show notes and chapters', 'How do I record a track?', 'Save mix and publish']
  }
  if (ctx.desk === 'topic') {
    return ['Create episode from topic', 'What is the next topic?', 'How do I write a blog?']
  }
  if (ctx.desk === 'post') {
    return ['How do I publish a post?', 'Survivor consent', 'What is the next blog?']
  }
  const hit = PATH_CHIPS.find((row) => {
    if (row.prefix.includes('?')) return false
    return ctx.pathname === row.prefix || ctx.pathname.startsWith(row.prefix + '/')
  })
  return hit?.chips || PATH_CHIPS[PATH_CHIPS.length - 1].chips
}
