export type CompetitorOutcomeKind = 'dollars' | 'reach' | 'leads' | 'ratio' | 'qualitative'

export type CompetitorCampaign = {
  org: string
  category: string
  related_why: string
  campaign: string
  year: string
  platforms: string[]
  objective: 'fundraising' | 'awareness' | 'lead_gen' | 'p2p'
  outcome_kind: CompetitorOutcomeKind
  outcome_value: number | null
  outcome_label: string
  what_worked: string
  copy_for_fitf: string
  avoid: string
  dignity: string
  sources: { title: string; url: string }[]
}

export const COMPETITOR_CAMPAIGNS: CompetitorCampaign[] = [
  {
    org: 'Polaris Project',
    category: 'National hotline / trafficking systems',
    related_why: 'Operates the U.S. National Human Trafficking Hotline — closest national peer on survivor response.',
    campaign: 'DIY + Facebook / birthday P2P fundraisers',
    year: '2022–2025',
    platforms: ['Facebook Fundraisers', 'owned P2P', 'Twitch / Tiltify'],
    objective: 'p2p',
    outcome_kind: 'dollars',
    outcome_value: 168127400,
    outcome_label: '$1.68M individual gifts in 2024 (all channels, not ads-only)',
    what_worked: 'Make it easy for supporters to fundraise on Facebook, the website, and livestreams. Toolkit language is pre-approved so volunteers do not improvise graphic stories.',
    copy_for_fitf: 'Ship advocate pages + a one-page language kit. Paid ads should send people into those P2P pages, not try to close the gift inside Meta checkout.',
    avoid: 'Do not let volunteer ads describe sexual violence. Polaris forbids that imagery in social fundraising.',
    dignity: 'Social content promoting Polaris may not feature sexual violence, exploitation, or abuse.',
    sources: [
      { title: 'Polaris Fundraise', url: 'https://polarisproject.org/fundraise/' },
      { title: 'Polaris DIY Fundraising Toolkit (PDF)', url: 'https://polarisproject.org/wp-content/uploads/2022/09/Polaris-DIY-Fundraising-Toolkit.pdf' },
      { title: 'Polaris 2024 annual report', url: 'https://polarisproject.org/wp-content/uploads/2025/08/Polaris-Annual-Report-2024-rev.pdf' },
    ],
  },
  {
    org: 'International Justice Mission',
    category: 'Global anti-trafficking / OSEC',
    related_why: 'Largest well-documented paid fundraising ads in the sector.',
    campaign: 'Holiday Gift Catalog — Feathr display + search + retargeting',
    year: '2020',
    platforms: ['Display', 'Paid search', 'Email mapping', 'Retargeting'],
    objective: 'fundraising',
    outcome_kind: 'dollars',
    outcome_value: 10950000,
    outcome_label: '$109,500 attributed to display ads in seven weeks',
    what_worked: 'Stacked retargeting of ijm.org visitors with extra creatives, email-list matching, and search on “gifts that give back” / charitable gifts. Catalog SKUs beat a generic donate ask.',
    copy_for_fitf: 'Build a small impact catalog (safe housing night, workforce week, advocate hour) and retarget donate-page visitors. Search on branded + “Ohio donate trafficking survivors”.',
    avoid: 'Do not wait for a single cold Meta prospecting campaign to beat catalog + retargeting.',
    dignity: 'Catalog copy should name programs, not graphic rescue scenes.',
    sources: [
      { title: 'IJM raises over $100k with digital ads', url: 'https://www.iaee.com/2022/12/22/ijm-raises-over-100k-with-digital-ads-in-year-end-campaign/' },
    ],
  },
  {
    org: 'IJM + A21 + ECPAT International',
    category: 'Global anti-trafficking awareness',
    related_why: 'Highest-reach Meta trafficking campaign on record; A21 and ECPAT are category peers.',
    campaign: 'Break Free to Fly (AR / VR + paid social)',
    year: '2022',
    platforms: ['Instagram', 'Facebook', 'Horizon Worlds'],
    objective: 'awareness',
    outcome_kind: 'reach',
    outcome_value: 10000000,
    outcome_label: '~10M people reached; 27M impressions in four weeks (Philippines ads)',
    what_worked: 'Platform partnership + immersive creative drove reach that cash media could not buy at this scale. Awareness, not donate ROAS.',
    copy_for_fitf: 'Use Meta for reach only when a partner is paying or when the KPI is awareness. Do not score this style of ad on first-gift ROAS.',
    avoid: 'Do not recreate confinement / trafficking reenactments for FITF ads. High reach, high survivor-risk.',
    dignity: 'Survivor voices were used in an immersive reenactment of confinement. FITF dignity gates should block this pattern.',
    sources: [
      { title: 'Meta partners with IJM', url: 'https://www.ijm.org/news/meta-partners-ijm-immersive-awareness-campaign' },
      { title: 'IJM Philippines recap', url: 'https://www.ijm.org.ph/articles/meta-campaign-in-collaboration-with-ijm-reaches-ten-million' },
    ],
  },
  {
    org: 'A21',
    category: 'Abolition / awareness',
    related_why: 'Global anti-trafficking brand; co-sponsor of Break Free to Fly.',
    campaign: 'Walk For Freedom + Meta partnership awareness',
    year: '2022–2025',
    platforms: ['Meta', 'Owned events', 'P2P'],
    objective: 'awareness',
    outcome_kind: 'qualitative',
    outcome_value: null,
    outcome_label: 'Awareness + event P2P; no public ROAS disclosed',
    what_worked: 'Event-tied walking campaigns give supporters a shareable action. Ads work as amplification of an owned moment, not a standalone donate unit.',
    copy_for_fitf: 'Pair any paid burst with a dated Ohio moment (Giving Tuesday, housing match, podcast drop) so the ad has somewhere concrete to land.',
    avoid: 'Do not run evergreen “end trafficking” ads with no offer, no match, and no next step.',
    dignity: 'Keep action-oriented creative. Do not use shock imagery to manufacture urgency.',
    sources: [
      { title: 'Meta × IJM / A21 / ECPAT', url: 'https://www.ijm.org/news/meta-partners-ijm-immersive-awareness-campaign' },
    ],
  },
  {
    org: 'Love146',
    category: 'Child trafficking prevention + survivor care',
    related_why: 'Care model closest to FITF’s survivor-centered mission.',
    campaign: 'Donate your birthday — Facebook Fundraisers',
    year: 'ongoing',
    platforms: ['Facebook Fundraisers', 'Owned give page'],
    objective: 'p2p',
    outcome_kind: 'qualitative',
    outcome_value: null,
    outcome_label: 'Organic P2P, not paid ads (public ROAS not disclosed)',
    what_worked: 'Birthday fundraisers piggyback on a moment supporters already share. Low creative cost, high trust from friends-of-friends.',
    copy_for_fitf: 'Prompt advocates to start birthday / workplace fundraisers that land on FITF campaign pages. Paid ads can recruit advocates, not replace them.',
    avoid: 'Do not spend paid budget trying to recreate friend-to-friend social proof.',
    dignity: 'Keep asks about care and prevention, not graphic child exploitation.',
    sources: [
      { title: 'Love146 ways to give', url: 'https://love146.org/ways-to-give/' },
    ],
  },
  {
    org: 'Shared Hope International',
    category: 'Child sex trafficking prevention',
    related_why: 'U.S. prevention + demand work; documented paid-lead ads.',
    campaign: 'Weekend Warrior — digital ads into CRM',
    year: '2020',
    platforms: ['Digital ads', 'Pardot / Salesforce'],
    objective: 'lead_gen',
    outcome_kind: 'leads',
    outcome_value: 765,
    outcome_label: '765 new advocates in six weeks from ads connected to CRM',
    what_worked: 'Ads sold a 15-minute weekly action, not a gift. New leads were immediately put on a nurture track. CRM was the product; ads were the top of funnel.',
    copy_for_fitf: 'Run a lead-gen ad to “get the monthly advocate kit” / podcast / newsletter, then ask for money on email 3–5. Log those later gifts as LTV, not first-click ROAS.',
    avoid: 'Do not orphan ad leads in a spreadsheet. Shared Hope only worked because ads wrote into the marketing cloud.',
    dignity: 'Equip busy supporters. Do not require them to consume traumatic content to “qualify”.',
    sources: [
      { title: 'SSIR: Shared Hope digital tools', url: 'https://ssir.org/articles/entry/invading_the_darkness_of_child_sex_trafficking' },
    ],
  },
  {
    org: 'Truckers Against Trafficking',
    category: 'Industry training + reporting',
    related_why: 'Ohio roads / Midwest freight are in TAT’s operating picture; industry-specific fundraising.',
    campaign: 'Everyday Heroes truck auctions + Facebook missing-child amplification',
    year: '2014–2023',
    platforms: ['Industry events', 'Facebook organic', 'Video'],
    objective: 'fundraising',
    outcome_kind: 'dollars',
    outcome_value: 32800000,
    outcome_label: 'Single auction high-water $328k; earlier trucks $83k and $162k',
    what_worked: 'Fundraise inside a community that already has identity (truckers), with a physical object and a celebrity-in-industry video. Facebook used for recovery posts with NCMEC, not donate ads — 70% of profiled missing children recovered in the 2014 partnership window.',
    copy_for_fitf: 'Ohio trades, churches, and first-responder audiences will outperform generic national lookalikes. Build one industry-specific offer per year.',
    avoid: 'Do not use missing-child photos in paid donate ads. TAT used those posts for recovery, not revenue.',
    dignity: 'Victim identification posts are a law-enforcement tool. Never a fundraising creative.',
    sources: [
      { title: 'Inland Everyday Heroes auctions', url: 'https://www.inland-group.com/i-care/everyday-heroes-truck-auctions/' },
      { title: 'TAT 2014 annual report (PDF)', url: 'https://tatnonprofit.org/wp-content/uploads/tat_annual_report_2014.pdf' },
    ],
  },
  {
    org: 'RAINN',
    category: 'Sexual violence hotline (adjacent)',
    related_why: 'National crisis-line peer; early Facebook donate product partner; matching gifts.',
    campaign: 'Facebook donate feature + Thrive Together $10M',
    year: '2013 / 2021',
    platforms: ['Facebook donate', 'Campaign video', 'Major gifts'],
    objective: 'fundraising',
    outcome_kind: 'dollars',
    outcome_value: 1000000000,
    outcome_label: '$10M Thrive Together goal; early FB donate + $30k match on launch gifts',
    what_worked: 'Platform-native donate button + a public match + a two-year named campaign with a video. Social proof (newsfeed stories after giving) was the product Facebook was selling.',
    copy_for_fitf: 'Always attach a match and a named campaign to paid traffic. Zeffy 0% fees is the FITF equivalent of Facebook’s fee waiver — say that in the ad.',
    avoid: 'A donate button without a match, a deadline, or a named fund underperforms.',
    dignity: 'Crisis-line orgs lead with help is available, not graphic assault detail.',
    sources: [
      { title: 'Facebook selects RAINN for donation feature', url: 'https://rainn.org/news/facebook-selects-rainn-new-donation-feature' },
      { title: 'Thrive Together $10M', url: 'https://ictnews.org/the-press-pool/rainn-launches-thrive-together-two-year-10-million-strategic-fundraising-initiative/' },
    ],
  },
  {
    org: 'Covenant House',
    category: 'Youth housing + trafficking',
    related_why: 'Housing for trafficked young people — same restricted-fund story FITF tells.',
    campaign: 'Just Like A Girl You Know — $10M housing plan',
    year: '2016',
    platforms: ['Video', 'Major campaign', 'Press'],
    objective: 'fundraising',
    outcome_kind: 'dollars',
    outcome_value: 1000000000,
    outcome_label: '$10M campaign; $5M already raised at launch',
    what_worked: 'Concrete housing outcome (“a home for young women starting over”) beat abstract “end trafficking.” Video title treated the girl as someone the donor already knows — proximity, not spectacle.',
    copy_for_fitf: 'Lead ads with a housing night / workforce week, not a national statistic. Name the Ohio place.',
    avoid: 'Do not use “rescued girl” stock photography. Covenant House’s frame is aftercare and housing.',
    dignity: 'Proximity without identifying a real survivor in the creative.',
    sources: [
      { title: 'CBC: Covenant House trafficking campaign', url: 'https://www.cbc.ca/news/canada/toronto/covenant-house-trafficking-1.3411253' },
    ],
  },
  {
    org: 'NCMEC',
    category: 'Missing & exploited children',
    related_why: 'National child-exploitation response; Cybertipline; TAT partnership.',
    campaign: 'High-risk missing children amplification with TAT',
    year: '2014–ongoing',
    platforms: ['Facebook organic', 'Law-enforcement partners'],
    objective: 'awareness',
    outcome_kind: 'ratio',
    outcome_value: 70,
    outcome_label: '70% of 27 profiled children recovered in the 2014 TAT window',
    what_worked: 'Distribution of identification posts through a trusted industry audience. This is a recovery channel, not a fundraising funnel.',
    copy_for_fitf: 'Do not run NCMEC-style missing-person creative as donate ads. If FITF ever shares a recovery post, it is unpaid, consented, and not attached to a gift ask.',
    avoid: 'Paid media that uses a child’s face to raise money.',
    dignity: 'Hard no. Victim identification ≠ fundraising.',
    sources: [
      { title: 'TAT 2014 annual report (PDF)', url: 'https://tatnonprofit.org/wp-content/uploads/tat_annual_report_2014.pdf' },
    ],
  },
  {
    org: 'Freedom Network USA',
    category: 'Survivor-led national coalition',
    related_why: 'Survivor-leadership peer; policy + training, not spectacle.',
    campaign: 'Facebook Fundraisers + DAF Direct',
    year: 'ongoing',
    platforms: ['Facebook Fundraisers', 'DAF Direct'],
    objective: 'p2p',
    outcome_kind: 'qualitative',
    outcome_value: null,
    outcome_label: 'No public paid-ad ROAS; fundraisers + DAF as primary digital give paths',
    what_worked: 'Meet donors where the money already sits (DAFs) and where friends already fundraise (Facebook). Messaging is about training professionals and survivor policy voice.',
    copy_for_fitf: 'Add DAF language to landing pages that paid search will hit. Keep ads about aftercare capacity, not raid footage.',
    avoid: 'Do not mimic “raid and rescue” creative from other brands.',
    dignity: 'Survivor voice in policy, not as a prop in ads.',
    sources: [
      { title: 'Freedom Network USA donate', url: 'https://freedomnetworkusa.org/join-us/donate/' },
    ],
  },
  {
    org: 'ECPAT-USA (PACT)',
    category: 'Child trafficking / travel industry',
    related_why: 'U.S. child-trafficking advocacy; GivingTuesday Meta matching case.',
    campaign: 'GivingTuesday Facebook match (Gates + Meta)',
    year: '2017',
    platforms: ['Facebook Fundraisers', 'Donate button', 'Live'],
    objective: 'fundraising',
    outcome_kind: 'dollars',
    outcome_value: 5000000,
    outcome_label: 'Up to $50k matched (or $1k per fundraiser) on GivingTuesday',
    what_worked: 'Borrowed match from Facebook + Gates. Three actions: start a fundraiser, add a donate button to a post, give on the Page. Fees waived that day.',
    copy_for_fitf: 'Calendar a GivingTuesday burst. Put the match in the first line of the ad. Point traffic at a live FITF campaign page, not the generic donate form.',
    avoid: 'A GivingTuesday ad with no match and no thermometer.',
    dignity: 'Industry prevention framing (travel, hospitality) is safer than victim imagery.',
    sources: [
      { title: 'ECPAT-USA GivingTuesday 2017', url: 'https://www.wearepact.org/blog/2017/11/21/this-givingtuesday-you-can-help-end-child-trafficking' },
    ],
  },
  {
    org: 'Nomi Network',
    category: 'Economic empowerment / trafficking',
    related_why: 'Rare public Meta-ads ROAS case in this issue area.',
    campaign: 'Meta ads with creative testing (Omneky)',
    year: '2021–2022',
    platforms: ['Meta'],
    objective: 'fundraising',
    outcome_kind: 'ratio',
    outcome_value: 2,
    outcome_label: '2× donations; 30% lower cost per donation after creative testing',
    what_worked: 'High volume of creative tests, lookalike audiences from engaged donors, holiday-specific copy. Message matched audience segment instead of one brand ad.',
    copy_for_fitf: 'Never run one creative. Test 5–10 dignity-safe variants (housing, workforce, match, podcast) against lookalikes of actual donors, not “interested in human trafficking”.',
    avoid: 'Interest targeting on “human trafficking” pulls rubberneckers. Lookalikes of donors pull donors.',
    dignity: 'Test headlines and offers, not graphic images.',
    sources: [
      { title: 'Omneky × Nomi Network', url: 'https://www.omneky.com/case-studies/how-nomi-network-increased-human-trafficking-awareness-and-donation-quanitity-through-fb-ads-with-omneky' },
      { title: 'CaseStudies.com recap', url: 'https://www.casestudies.com/company/omneky/case-study/nomi-network-increases-donations-2x-and-cuts-cost-per-donation-30-with-omneky' },
    ],
  },
  {
    org: 'Gracehaven (Ohio)',
    category: 'Ohio survivor housing for minors',
    related_why: 'Closest Ohio specialty-care peer.',
    campaign: 'Over the Edge rappelling fundraiser',
    year: '2015–2025',
    platforms: ['Owned event', 'GiveCloud', 'Local press / social'],
    objective: 'fundraising',
    outcome_kind: 'dollars',
    outcome_value: 22700000,
    outcome_label: '>$227k in one year; >$2.5M since 2015',
    what_worked: 'Experiential local event with a public goal and a deadline. Social is amplification of a physical stunt, not the fundraiser itself.',
    copy_for_fitf: 'Ohio experiential + matching will beat national cold ads. Use paid geo-ads only to fill the event / match, then retarget attendees.',
    avoid: 'Do not try to out-spend national brands on cold Meta prospecting from Ohio.',
    dignity: 'Event creative can be joyful. Leave trauma out of the invite.',
    sources: [
      { title: 'Columbus Underground: Gracehaven Over the Edge', url: 'https://columbusunderground.com/gracehaven-raises-over-200000-in-annual-skyscraper-rappelling-fundraiser-ak1/' },
    ],
  },
]

export const COMPETITOR_PLAYBOOK = [
  {
    title: 'Buy intent, not outrage',
    body: 'Paid search and branded donate keywords return ~$2.48 per $1. Shock trafficking ads buy cheap clicks and expensive problems.',
  },
  {
    title: 'Retarget people who already care',
    body: 'IJM’s catalog worked because the audience had already been on the site. FITF should retarget /donate, /campaigns, and podcast listeners before prospecting.',
  },
  {
    title: 'Sell a catalog or a match, not “end trafficking”',
    body: 'Concrete SKUs (housing night, workforce week) and a visible match outperform abstract abolition copy. RAINN, ECPAT, and Covenant House all named a fund.',
  },
  {
    title: 'Use Meta for acquisition, search for return',
    body: 'Sector Meta fundraising ROAS is $0.76. That is a first-gift loss. It can still be right if 12-month LTV > CPA. Search is where FITF should expect profit.',
  },
  {
    title: 'P2P is organic; ads recruit the fundraisers',
    body: 'Polaris, Love146, and Freedom Network make Facebook Fundraisers the product. Paid ads should create advocates, not replace friend-to-friend asks.',
  },
  {
    title: 'Never fundraise with a survivor’s face or a missing-child poster',
    body: 'TAT/NCMEC recovery posts and Break Free to Fly reenactments are not FITF creative. Dignity gates stay on for ads the same way they stay on for campaigns.',
  },
]
